spring:
  jpa:
    hibernate:
      ddl-auto: update # or create-drop for recreation of tables on every start
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
